// layout.tsx
import "@/styles/globals.css";
import { inter, myFont } from "../styles/fonts";
import { type Metadata } from "next";
import { Header } from "@/components/layout/Header/Header";
import { Footer } from "@/components/layout/Footer/Footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.variable} ${myFont.variable}`}>
      <body className="bg-primary">
        <div className="container mx-auto px-6 py-6 sm:px-28 sm:py-16">
          <Header />
          <main className="py-3 sm:py-5">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
